
version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '5000:5000'

  jenkins:
    build: .
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins_workspace:/home/jenkins/test
      - jmeter_data:/opt/apache-jmeter-5.6.3
      - taurus_data:/opt/taurus
    environment:
      - JENKINS_OPTS=--httpPort=8080
    restart: unless-stopped

volumes:
  jenkins_home:
    driver: local
  jenkins_workspace:
    driver: local
  jmeter_data:
    driver: local
  taurus_data:
    driver: local
